blank_issues_enabled: false
contact_links:
  - name: Questions & Discussions
    url: https://github.com/WFStudio-app/Asombi/discussions
    about: Ask questions and discuss Asombi OS here
  - name: Truck Package Requests
    url: https://github.com/WFStudio-app/Asombi/discussions
    about: Request new packages for Truck
