# Asombi Official Package Repository
# Format: TOML

[repo]
name = "Asombi Official"
maintainer = "WFWorld"
updated = "2026-06-29"

[packages.hello-wiz]
version = "1.0.0"
description = "Test package for Wizzor"
url = "https://raw.githubusercontent.com/WFStudio-app/Asombi/main/packages/hello-wiz-1.0.0.sh"
sha256 = ""
size = "1 KB"
depends = []
license = "MIT"
